export const initialValuesFormIndividual = {
  nome: "",
  apelido: "",
  cpf: "",
  dataNascimento: "",
  estadoCivil: "",
  rg: "",
  orgaoEmissor: "",
  ufRg: "",
  cnh: "",
  seguranca: "",
  cei: "",
  email: "",
  telefone: "",
  celular: "",
  cep: "",
  cidade: "",
  uf: "",
  endereco: "",
  numero: "",
  complemento: "",
  bairro: "",
  observacao: "",
}

export const initialValuesFormCorporate = {
  razaoSocial: "",
  nomeFantasia: "",
  cnpj: "",
  ativo: false,
  contribuinte: "",
  inscricaoEstadual: "",
  inscricaoMunicipal: "",
  email: "",
  nomeResponsavel: "",
  cpf: "",
  dataNascimento: "",
  telefone: "",
  celular: "",
  emailResponsavel: "",
  cep: "",
  cidade: "",
  uf: "",
  endereco: "",
  numero: "",
  complemento: "",
  bairro: "",
  observacao: "",
}